### ISSUE TITLE
Arcade Drive Fix

### ISSUE THREAD

**Issue by Infinit3PI** [Robo4607/Testing#3]
test and figure out how to either edit/fix or create our own KiwiArcadeDrive function.

**Comment by Penchant** [comment]
I believe either my version or the other team's version should be successful, however, I have yet to test either.

**Comment by Penchant** [comment]
Must deploy to be 100% but I believe we are good to go. Will be closing this issue.

**Comment by EthyMoney** [comment]
So Ima tell you a story. This one time, I stayed up late like you, and
found out it can actually such when I gots to get up at 7am. Suddenly it
hit me! I can sleep, and it's a wonderful thing. Highly recommend it bro-ski
